### ISSUE TITLE
502 gateaway

### ISSUE THREAD

**Issue by Kolhax** [MainSilent/MailTm#3]

**Comment by Kolhax** [comment]
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://api.mail.tm/domains

**Comment by Kolhax** [comment]
```
def listener(message):
    print(message['subject'])
    with open("mail.txt", "w") as f:
        f.write(message['subject'][:6])
        f.close()
```

**Comment by Kolhax** [comment]
```
    test = Email()
    test.register()
    email = str(test.address)
```

**Comment by MainSilent** [comment]
It's working fine for me, This library uses [mail.tm](https://mail.tm) API, If you have no issue using that website the library should work, Can you send full code?
